#!/bin/bash -e

# https://github.com/vmware/govmomi/blob/v0.17.1-1-g49c710b/govc/USAGE.md
# https://github.com/vmware/govmomi/tree/49c710b39ee6de3810ee8130b32361fb8ca1bcb8/govc

export GOVC_HOST="70.0.0.67"
export GOVC_USERNAME="root"
export GOVC_PASSWORD=$(cat .esx_password)
export GOVC_INSECURE=true
export GOVC_URL="https://${GOVC_HOST}/sdk"
export GOVC_DATASTORE="HDD"
GOVC=../bin/govc

cpus="1"
mem="4096"
disk="4096"
template="ubuntu-template"
ssh_key=".vagrant/machines/${2}/vmware_esxi/private_key"


usage() { echo "Usage: $0 $(gawk '/^\s*[a-z]*)/ { gsub(/)/,""); gsub(/\s/, "");  printf("|%s", $0); } END { printf("|\n") }' $0) <name>"; exit 1; }
check() { [ -x "$(command -v $1)" ] || { echo "Error: $1 is not installed, aborting"; exit 1; } }
for cmd in $GOVC; do check $cmd; done


case $1 in
    create)
        $GOVC vm.clone -vm "${template}" "${2:?USAGE: Name not specified}"
        ;;

    delete)
        ;;
    getip)
        $GOVC vm.ip -a "${2:?USAGE: Name not specified}"
        ;;
    ssh)
        IP=$($GOVC vm.ip -a ${2:?USAGE: Name not specified})
        ssh ${ssh_key:+-i ${ssh_key}} vagrant@${IP:?Unable to find IP address for the host}
        ;;
    list)
        $GOVC ls vm | awk -F / '{ print $NF }' | sort
        ;;
    info)
        $GOVC vm.info "${2:?USAGE: Name not specified}"
        ;;

    *)
        usage
        ;;
esac

