#!/bin/bash -e

: ${zone:="us-west1-a"}
: ${proj:="portworx-eng"}
: ${type:="n1-standard-4"}
: ${image:="ubuntu-1604-xenial-v20180814"}
: ${image_prj:="ubuntu-os-cloud"}
: ${script:="run/ubuntu-run.sh"}
: ${boot_size:="60"}
: ${boot_type:="pd-ssd"}
: ${data_size="100"}
: ${data_type:="pd-ssd"}
: ${owner:="as"}
# local_ssd=NVME

usage() { echo "Usage: $0 $(gawk '/^\s*[a-z]*)/ { gsub(/)/,""); gsub(/\s/, "");  printf("|%s", $0); } END { printf("|\n") }' $0) <name>"; exit 1; } 
check() { [ -x "$(command -v $1)" ] || { echo "Error: $1 is not installed, aborting"; exit 1; } }
for cmd in gcloud curl; do check $cmd; done

account=$(gcloud info | awk '/^Account:/ { gsub(/(\[|\])/, "", $2); print $2; }')
[ $account ] || { echo "GCP Account Info Not Found"; exit 1; }

export CLOUDSDK_CORE_DISABLE_PROMPTS=1
gcloud config set compute/zone $zone &>/dev/null
gcloud config set project $proj &>/dev/null

case $1 in
    create)
        #n=0; for d in ${data_size}; do 
        #    disks="${disks} --disk=mode=rw,auto-delete=yes,size=${d},type=${data_type},name=${2}-${n}"
        #    n=$((n+1))
        #done

        gcloud compute instances create ${2:?USAGE: Name not specified} \
        --machine-type=${type} \
        --boot-disk-auto-delete \
        --boot-disk-size=${boot_size}GB \
        --boot-disk-type=${boot_type} \
        ${local_ssd:+--local-ssd=interface=${local_ssd}} \
        --image=${image} \
        --image-project=${image_prj} \
        --metadata-from-file startup-script=${script} \
        --labels=owner=${owner}

        n=0; for d in ${data_size}; do 
            gcloud compute disks create ${2}-d${n} --size=${d}GB --type=${data_type}
            gcloud compute instances attach-disk ${2} --disk ${2}-d${n}
            n=$((n+1))
        done
        
        set +e; until $0 ssh $2 '[ -f /var/lib/cloud/instance/user-init-finished ]' &>/dev/null; do sleep 30; done
        ;;
    delete)
        gcloud compute instances delete ${2:?USAGE: Name not specified} --delete-disks=all
        ;;
    start)
        gcloud compute instances start ${2:?USAGE: Name not specified}
        ;;
    stop)
        gcloud compute instances stop ${2:?USAGE: Name not specified}
        ;;
    ssh)
        name=${2:?USAGE: Name not specified}
        shift 2
        gcloud compute ssh ${name} --command="$*"
        ;;
    list)
        gcloud compute instances list --filter="zone:( ${zone} ) AND labels.owner=${owner}"
        ;;
    login)
        gcloud auth login
        ;;
    setup)
        export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
        echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install google-cloud-sdk
        gcloud init
        ;;
    *)
        usage
        ;;
esac

        
    
